---
title: "Resume"
author: "[YOUR NAME]"
date: "`r Sys.Date()`"
output:
  pagedown::html_resume:
    css: ['css/custom_resume.css', 'css/styles.css', 'resume']
    # set it to true for a self-contained HTML page but it'll take longer to render
    self_contained: true
---


```{r, include=FALSE}
knitr::opts_chunk$set(
  results='asis', 
  echo = FALSE
)
library(tidyverse)
library(glue)

# Set this to true to have links turned into footnotes at the end of the document
PDF_EXPORT <- FALSE

# Holds all the links that were inserted for placement at the end
links <- c()

source('parsing_functions.R')


# First let's get the data, filtering to only the items tagged as
# Resume items
position_data <- read_csv('positions.csv') %>% 
  filter(in_resume) %>% 
  mutate(
    # Build some custom sections by collapsing others
    section = case_when(
      section %in% c('research_positions', 'industry_positions') ~ 'positions', 
      section %in% c('projects') ~ 'projects',
      TRUE ~ section
    )
  ) 

```


Aside
================================================================================


Contact {#contact}
--------------------------------------------------------------------------------


- <i class="fa fa-envelope"></i> [your.email@asu.edu]
- <i class="fa fa-phone"></i> [(555) 555-5555]
- <i class="fa fa-github"></i> github.com/[your-github-id]
- <i class="fa fa-link"></i> [your-github-id.github.io/cv](https://your-github-id.github.io/cv)
- <i class="fa fa-map-marker"></i> Phoenix, AZ



Skills {#skills}
--------------------------------------------------------------------------------


```{r}
skills <- tribble(
  ~skill,                  ~level,
  "R / R Markdown",        4,
  "Salesforce",            4,
  "Excel & Google Sheets", 4,
  "Survey & Program Data", 3,
  "SQL",                   2
)
build_skill_bars(skills)
```



Certifications {#certifications}
--------------------------------------------------------------------------------

- IRB / Human Subjects Research certification
- Salesforce donor records and reporting



Disclaimer {#disclaimer}
--------------------------------------------------------------------------------

**Note:** this resume was built for a course assignment (PAF 514). Entries marked
*ASPIRATIONAL ENTRY* are fictional examples, not actual work history.

Made w/ [**pagedown**](https://github.com/rstudio/pagedown).

Last updated on `r Sys.Date()`.




Main
================================================================================

[YOUR NAME] {#title}
--------------------------------------------------------------------------------

```{r}
intro_text <- "Graduate student in Program Evaluation & Data Analytics at Arizona State University,
currently working in nonprofit administration and development research. I keep donor and program
records accurate in Salesforce, research giving prospects for a development team, and analyze
program data in R.

Looking for a program evaluation or data analyst role in the nonprofit or public sector.
"

cat(sanitize_links(intro_text))
```



Education {data-icon=graduation-cap data-concise=true}
--------------------------------------------------------------------------------

```{r}
position_data %>% print_section('education')
```



Experience {data-icon=suitcase}
--------------------------------------------------------------------------------

```{r}
position_data %>% print_section('positions')
```



Projects {data-icon=laptop}
--------------------------------------------------------------------------------

```{r}
position_data %>% print_section('projects')
```
